package Main;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kurt Pascua
 */

public class AboutDevelopers extends javax.swing.JFrame {
    int count;
    /**
     * Creates new form AboutPage
     */
    public AboutDevelopers() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/HUMSS_LOGO.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdminPage1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        btnPolicies = new javax.swing.JLabel();
        linkDave = new javax.swing.JLabel();
        linkKurt = new javax.swing.JLabel();
        linkLouis = new javax.swing.JLabel();
        linkKeane = new javax.swing.JLabel();
        linkJill = new javax.swing.JLabel();
        linkJasper = new javax.swing.JLabel();
        linkSirRoi = new javax.swing.JLabel();
        linkJonard = new javax.swing.JLabel();
        lblWrapper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About ");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 80, 49));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminPage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminPage1MouseClicked(evt);
            }
        });
        jPanel1.add(btnAdminPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 100, 90));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, 65, 22));

        btnPolicies.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnPolicies.setForeground(new java.awt.Color(255, 255, 255));
        btnPolicies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPolicies.setText("POLICIES");
        btnPolicies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPoliciesMouseClicked(evt);
            }
        });
        jPanel1.add(btnPolicies, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 633, 100, 30));

        linkDave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDaveMouseClicked(evt);
            }
        });
        jPanel1.add(linkDave, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 315, 80, 80));

        linkKurt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkKurtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkKurtMouseEntered(evt);
            }
        });
        jPanel1.add(linkKurt, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 180, 80, 80));

        linkLouis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLouisMouseClicked(evt);
            }
        });
        jPanel1.add(linkLouis, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 480, 80, 80));

        linkKeane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkKeaneMouseClicked(evt);
            }
        });
        jPanel1.add(linkKeane, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 80, 80));

        linkJill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkJillMouseClicked(evt);
            }
        });
        jPanel1.add(linkJill, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 80, 80));

        linkJasper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkJasperMouseClicked(evt);
            }
        });
        jPanel1.add(linkJasper, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 80, 80));

        linkSirRoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSirRoiMouseClicked(evt);
            }
        });
        jPanel1.add(linkSirRoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 80, 80));

        linkJonard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkJonardMouseClicked(evt);
            }
        });
        jPanel1.add(linkJonard, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 315, 80, 80));

        lblWrapper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/aboutdevelopers.png"))); // NOI18N
        jPanel1.add(lblWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminPage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminPage1MouseClicked
        // TODO add your handling code here:
        Landing_Page LP = new Landing_Page();
        LP.show();

        dispose();
    }//GEN-LAST:event_btnAdminPage1MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        AboutPage AP = new AboutPage();
        AP.show();

        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnPoliciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPoliciesMouseClicked
        // TODO add your handling code here:
        AboutPolicies AP = new AboutPolicies();
        AP.show();
        
        dispose();
    }//GEN-LAST:event_btnPoliciesMouseClicked

    private void linkKurtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkKurtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_linkKurtMouseEntered

    private void linkKurtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkKurtMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/tohsaka.rin.7771/";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkKurtMouseClicked

    private void linkSirRoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSirRoiMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/roroi.francisco";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkSirRoiMouseClicked

    private void linkJonardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkJonardMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/whoisjonard";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkJonardMouseClicked

    private void linkDaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDaveMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/profile.php?id=100085935548631";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkDaveMouseClicked

    private void linkJasperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkJasperMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/jasper.marco.587";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkJasperMouseClicked

    private void linkLouisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLouisMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/JohnLouis.Uchiha";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkLouisMouseClicked

    private void linkKeaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkKeaneMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/kiyxn";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkKeaneMouseClicked

    private void linkJillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkJillMouseClicked
        // TODO add your handling code here:
        String hyperlink = "https://www.facebook.com/tyronia.kisha";  //hyperlinks

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(hyperlink));
                }
            }
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            // Handle any exceptions that occur during the process
        }
    }//GEN-LAST:event_linkJillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AboutDevelopers AP = new AboutDevelopers();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutDevelopers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutDevelopers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutDevelopers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutDevelopers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutDevelopers().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdminPage1;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnPolicies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWrapper;
    private javax.swing.JLabel linkDave;
    private javax.swing.JLabel linkJasper;
    private javax.swing.JLabel linkJill;
    private javax.swing.JLabel linkJonard;
    private javax.swing.JLabel linkKeane;
    private javax.swing.JLabel linkKurt;
    private javax.swing.JLabel linkLouis;
    private javax.swing.JLabel linkSirRoi;
    // End of variables declaration//GEN-END:variables
}
