package Main;

import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kurt Pascua
 */

public class AboutPage extends javax.swing.JFrame {
    int count;
    /**
     * Creates new form AboutPage
     */
    public AboutPage() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/HUMSS_LOGO.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdminPage1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        btnDevs = new javax.swing.JLabel();
        btnPolicies = new javax.swing.JLabel();
        lblWrapper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About ");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 80, 49));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminPage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminPage1MouseClicked(evt);
            }
        });
        jPanel1.add(btnAdminPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 110, 110));

        btnBack.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("BACK");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 40));

        btnDevs.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnDevs.setForeground(new java.awt.Color(255, 255, 255));
        btnDevs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDevs.setText("DEVELOPERS");
        btnDevs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDevsMouseClicked(evt);
            }
        });
        jPanel1.add(btnDevs, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 633, 100, 30));

        btnPolicies.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnPolicies.setForeground(new java.awt.Color(255, 255, 255));
        btnPolicies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPolicies.setText("POLICIES");
        btnPolicies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPoliciesMouseClicked(evt);
            }
        });
        jPanel1.add(btnPolicies, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 633, 100, 30));

        lblWrapper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aboutpage.png"))); // NOI18N
        jPanel1.add(lblWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminPage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminPage1MouseClicked
        // TODO add your handling code here:
        Landing_Page LP = new Landing_Page();
        LP.show();

        dispose();
    }//GEN-LAST:event_btnAdminPage1MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Landing_Page LP = new Landing_Page();
        LP.show();

        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnDevsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevsMouseClicked
        // TODO add your handling code here:
        AboutDevelopers AD = new AboutDevelopers();
        AD.show();
        
        dispose();
    }//GEN-LAST:event_btnDevsMouseClicked

    private void btnPoliciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPoliciesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoliciesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AboutPage AP = new AboutPage();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutPage().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdminPage1;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnDevs;
    private javax.swing.JLabel btnPolicies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWrapper;
    // End of variables declaration//GEN-END:variables
}
